[theme]
inherit = "basic"
stylesheets = [
#    "css/img.css",
    "css/pdj.css",
#    "css/darker.css",
]

[options]
analytics_id = ''
sticky_navigation = false
style = "default"
logo_width = ''
logo_height = ''
search = 'show'
home_link = 'show'
home_menu_item = 'hide'
home_menu_item_label = ''
